version: "3"
services:
  db:
    image: "postgres:latest"
    container_name: "postgres12"
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
